# Use root/example as user/password credentials
version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linklink_docker_compose
    environment:
      - PORT=${PORT}
    ports:
      - '3003:3003'
    volumes:
      - ./src:/app/src